PLAT-104266: Update webosauto template for Enact 3.2.6 and Agate 1.0
enactjs/templates pull request #23
Opened 2020-04-23 22:16 UTC by sugardave

Updating versions for the templates that use `agate`

2020-04-30 23:13 UTC, webOS101 approved these changes

2020-05-01 15:36 UTC, ryanjduffy requested changes
Just a "blocking until 1.0" review :)

2020-11-02 05:34 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/enactjs/templates?pullRequest=23) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla-assistant.io/enactjs/templates?pullRequest=23) before we can accept your contribution.<br/>**1** out of **2** committers have signed the CLA.<br/><br/>:white_check_mark: ybsung<br/>:x: Dave Freeman<br/><hr/>**Dave Freeman** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/enactjs/templates?pullRequest=23) it.</sub>

2020-11-02 05:36 UTC, ybsung approved these changes
LGTM

2020-11-02 09:51 UTC, 0x64 approved these changes

2020-11-02 09:53 UTC, merged