PLAT-113142: Use ilib-webos NPM package in webOS templates and framework setup
enactjs/templates pull request #24
Opened 2020-07-07 16:21 UTC by JayCanuck

* Update to ilib alias to `ilib-webos@^14.6.0-webos1`

Enact-DCO-1.0-Signed-off-by: Jason Robitaille <jason.robitaille@lge.com>

2020-07-28 18:13 UTC, germboy requested changes
Looks good - just had a question about which enact version we're updating to.

2020-07-28 18:13 UTC, germboy commented on packages/webostv/template/package.json
> +    "@enact/webos": "^3.3.0-alpha.11",
Would it make sense to update the enact deps to `3.3.1` at this point, now that we've officially released it?

2020-07-29 00:51 UTC, JayCanuck commented
Good point. Updated both the sandstone templates for `"^3.3.0"` range on Enact repos.  We'll need to update sandstone to `"^1.0.0"` range once that's published.

2020-07-30 17:35 UTC, germboy approved these changes
:lgtm:

2020-08-04 21:55 UTC, webOS101 approved these changes
:+1:

2020-08-04 21:55 UTC, merged