ENYO-5525 - Update templates to use 2.0.0
enactjs/templates pull request #3
Opened 2018-08-02 18:06 UTC by rundmt

Enact-DCO-1.0-Signed-off-by: Derek Tor <derek.tor@lge.com>

2018-08-02 18:06 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/enactjs/templates?pullRequest=3) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/enactjs/templates?pullRequest=3) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/enactjs/templates?pullRequest=3) it.</sub>

2018-08-02 21:28 UTC, ryanjduffy requested changes
Think we need to bump the package version as well for each of these

2018-08-02 21:31 UTC, ryanjduffy commented
Maybe we do that when we "release" them ... We don't have release process for these afaik.

2018-08-02 23:14 UTC, ryanjduffy approved these changes

2018-08-03 19:51 UTC, webOS101 approved these changes
👍 👍

2018-08-03 19:51 UTC, merged