WRP-9708: Update 'ri' description in CLI docs
enactjs/templates pull request #70
Opened 2023-04-11 06:56 UTC by hong6316

### Checklist

* [x] I have read and understand the [contribution guide](http://enactjs.com/docs/developer-guide/contributing/)
* [ ] A [CHANGELOG entry](http://enactjs.com/docs/developer-guide/contributing/changelogs/) is included
* [ ] At least one test case is included for this feature or bug fix
* [x] Documentation was added or is not needed
* [ ] This is an API breaking change

### Issue Resolved / Feature Added
[//]: # (Describe the issue resolved or feature added by this pull request)
Update 'ri' description in CLI docs

### Resolution
[//]: # (Does the code work as intended?)
[//]: # (What is the impact of this change and *why* was it made?)
- Add `basesize` description.
- Replace `less plugin` to `postcss-resolution-independence`

### Additional Considerations
[//]: # (How should the change be tested?)
[//]: # (Are there any outstanding questions?)
[//]: # (Were any side-effects caused by the change?)

### Links
[//]: # (Related issues, references)
WRP-9708

### Comments
Enact-DCO-1.0-Signed-off-by: Taeyoung Hong (taeyoung.hong@lge.com)

2023-04-12 22:58 UTC, MikyungKim commented on packages/agate/template/README.md
> +* `theme` _[object]_ - A simplified string name to extrapolate `fontGenerator`, `ri`, and `screenTypes` preset values from. For example, `"sandstone"`.
Why did you change agate to sandstone???

2023-04-12 22:59 UTC, MikyungKim commented on packages/cordova/template/README.md
> +* `theme` _[object]_ - A simplified string name to extrapolate `fontGenerator`, `ri`, and `screenTypes` preset values from. For example, `"sandstone"`.
Was this template moonstone or not?

2023-04-12 23:00 UTC, MikyungKim commented on packages/moonstone/template/README.md
> +* `theme` _[object]_ - A simplified string name to extrapolate `fontGenerator`, `ri`, and `screenTypes` preset values from. For example, `"sandstone"`.
Please don't make any changes to the theme names.

2023-04-12 23:01 UTC, MikyungKim requested changes
Please, don't make any changes to the theme name. It's based on the template's theme.
Where is the description for `baseSize`?

2023-04-13 01:22 UTC, seunghoh commented
Nice try, but I might want to rewrite the `ri` description not just modify this PR.

2023-04-13 01:22 UTC, closed without merging